version: "3.9"
services:
  model_train:
    build:
      context: .           
      dockerfile: Dockerfile
    runtime: nvidia   
    image: RD/yolo-dev:latest  # 可選：指定 build 完成後的映像名稱
    container_name: model_train
    working_dir: /app/Model_Train
    volumes:
      - ./Model_Train:/app/Model_Train
      - ./cache:/root/.cache
    stdin_open: true  # 允許容器保持開啟狀態，等待用戶輸入
    tty: true         # 幫容器分配一個虛擬終端機（terminal）
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - DISPLAY=${DISPLAY}
    command: bash

  hikvision_camera_platform:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: RD/yolo-dev:latest  
    container_name: hikvision_camera_platform
    working_dir: /app/hikvision_camera_platform
    volumes:
      - ./hikvision_camera_platform:/app/hikvision_camera_platform
      - /opt/MVS:/opt/MVS:ro
      - ./cache:/root/.cache
    stdin_open: true
    tty: true
    restart: always
    shm_size: '16gb'
    environment:
      # GPU 可見性 (如有用到)
      - NVIDIA_VISIBLE_DEVICES=all
      - MVCAM_COMMON_RUNENV=/opt/MVS/lib 
      # Linker 載入 .so 目錄
      - LD_LIBRARY_PATH=/opt/MVS/lib/64:/opt/MVS/bin:${LD_LIBRARY_PATH}
      # 讓 Python 找到 MvCameraControl_class.py（MvImport 資料夾）
      - PYTHONPATH=/opt/MVS/Samples/64/Python/MvImport:${PYTHONPATH}
      # 可執行 MVS 工具
      # - PATH=/opt/MVS/bin:${PATH}
    ports:
      - "7777:7777"
    privileged: true 
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: sleep 10000
    # command: python3 realtime_ui_V1.py
    # command: python3 realtime_ui._V2.py
    # command: python3 UI.py

  defect_inspection_prototype_x86:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: RD/yolo-dev:latest 
    container_name: defect_inspection_prototype_x86
    working_dir: /app/defect_inspection_prototype_x86
    volumes:
      - ./defect_inspection_prototype_x86:/app/defect_inspection_prototype_x86
      - /opt/MVS:/opt/MVS:ro
      - ./cache:/root/.cache
    stdin_open: true
    tty: true
    restart: always
    shm_size: '16gb'

    environment:
      # GPU 可見性 (如有用到)
      - NVIDIA_VISIBLE_DEVICES=all
      - MVCAM_COMMON_RUNENV=/opt/MVS/lib 
      # Linker 載入 .so 目錄
      - LD_LIBRARY_PATH=/opt/MVS/lib/64:/opt/MVS/bin:${LD_LIBRARY_PATH}
      # 讓 Python 找到 MvCameraControl_class.py（MvImport 資料夾）
      - PYTHONPATH=/opt/MVS/Samples/64/Python/MvImport:${PYTHONPATH}
      # 可執行 MVS 工具
      # - PATH=/opt/MVS/bin:${PATH}
    ports:
      - "7787:7787"
    privileged: true 
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # command: python3 prototype_UI.py
    command: sleep 10000

